import { useState, useId } from 'react'
import clsx from 'clsx'
import {
  Modal, Button, Tooltip,
  IconCodeOutline16, IconSparkle16, IconBrowseOutline16,
  IconCheckOutline16, IconCopyOutline16, IconChevronDownOutline14,
  IconRefreshOutline16
} from '@/components/ui'
import { useViewStore } from '@/store/useViewStore'
import type { ProjectResponse } from '@/types/project'
import type { TelemetrySessionExportItem } from './exportTelemetry'
import css from './SessionTraceModal.module.css'

/**
 * ============================================================================
 * BACKEND API SPECIFICATION NOTE (FOR BACKEND INTEGRATION)
 * ============================================================================
 * Endpoint: GET /api/projects/{projectId}/sessions/{sessionId}/trace
 * 
 * Expected Response Schema:
 * {
 *   "session_id": string,
 *   "project_id": string,
 *   "session_title": string,
 *   "model": string,
 *   "total_latency_ms": number,
 *   "llm_latency_ms": number,
 *   "sandbox_latency_ms": number,
 *   "ttft_ms": number,
 *   "throughput_tok_per_sec": number,
 *   "cache_hit_pct": number,
 *   "strategy": "Multi-hop Parallel" | "Single-hop Search" | "Direct Q&A",
 *   "nodes": [
 *     {
 *       "id": string,
 *       "node_index": number,
 *       "type": "user_prompt" | "sac_codegen" | "sandbox_exec" | "vector_retrieval" | "refinement_codegen" | "grounded_synthesis",
 *       "title": string,
 *       "subtitle": string,
 *       "duration_ms": number,
 *       "status": "success" | "warning" | "error",
 *       "details": {
 *         "thought"?: string,
 *         "code"?: string,
 *         "language"?: string,
 *         "stdout"?: string,
 *         "exit_code"?: number,
 *         "memory_mb"?: number,
 *         "chunks"?: Array<{ document: string; page: number; section: string; score: number; text_snippet: string }>,
 *         "citations"?: Array<{ id: number; source: string; page: number; quote: string; verified: boolean }>,
 *         "answer_snippet"?: string
 *       }
 *     }
 *   ]
 * }
 * ============================================================================
 */

export interface SessionTraceModalProps {
  open: boolean
  onClose: () => void
  session: TelemetrySessionExportItem | null
  project: ProjectResponse
}

interface TraceNode {
  id: string
  nodeIndex: number
  type: 'user_prompt' | 'sac_codegen' | 'sandbox_exec' | 'vector_retrieval' | 'refinement_codegen' | 'grounded_synthesis'
  title: string
  subtitle: string
  durationText: string
  status: 'success' | 'warning' | 'info'
  thought?: string
  code?: string
  stdout?: string
  exitCode?: number
  memoryMb?: number
  chunks?: Array<{ document: string; page: number; section: string; score: number; textSnippet: string }>
  citations?: Array<{ id: number; source: string; page: number; quote: string; verified: boolean }>
  answerSnippet?: string
}

export function SessionTraceModal({ open, onClose, session, project }: SessionTraceModalProps) {
  const { navigateToChat } = useViewStore()
  const [activeView, setActiveView] = useState<'tree' | 'raw'>('tree')
  const [expandedNodes, setExpandedNodes] = useState<Record<string, boolean>>({
    'node-1': true,
    'node-2': true,
    'node-3': true,
    'node-4': true,
    'node-5': true,
    'node-6': true,
  })
  const [copiedCodeId, setCopiedCodeId] = useState<string | null>(null)
  const titleId = useId()

  if (!session) return null

  // Generate realistic Search-as-Code execution graph nodes for this session
  const traceNodes: TraceNode[] = [
    {
      id: 'node-1',
      nodeIndex: 1,
      type: 'user_prompt',
      title: 'Lượt 1: Câu Hỏi Người Dùng (User Prompt)',
      subtitle: 'Người dùng yêu cầu phân tích đối chiếu điều khoản hợp đồng',
      durationText: '0ms',
      status: 'info',
      thought: `User Query: "${session.title}"`,
    },
    {
      id: 'node-2',
      nodeIndex: 2,
      type: 'sac_codegen',
      title: 'Turn 1: LLM Reasoning & Sinh Mã Python (Search-as-Code)',
      subtitle: 'Mô hình phân tích câu hỏi, lập kế hoạch sub-queries và sinh code tìm kiếm song song',
      durationText: '38.2s · 1.4K tokens',
      status: 'success',
      thought:
        'Kế hoạch: Câu hỏi yêu cầu đối chiếu các điều khoản bồi thường và chấm dứt hợp đồng. Tôi sẽ sinh mã Python gọi SaC SDK để tìm kiếm song song 2 chủ đề trong toàn bộ tài liệu dự án.',
      code: `# --- Search-as-Code Python Program (Generated by LLM) ---
import asyncio
from sac_sdk import search_vectors, rerank_results, filter_metadata

async def run_search():
    # 1. Parallel sub-queries for multi-hop comparative retrieval
    sub_queries = [
        "điều khoản bồi thường thiệt hại vi phạm hợp đồng kinh tế",
        "quy định chấm dứt hợp đồng trước hạn phạt cọc và nghĩa vụ thanh lý"
    ]
    
    # 2. Query Qdrant vector index concurrently
    tasks = [
        search_vectors(q, collection="project_${project.id}", top_k=6, min_score=0.80)
        for q in sub_queries
    ]
    raw_results = await asyncio.gather(*tasks)
    
    # 3. Flatten and Cross-Encoder Re-ranking
    all_chunks = [chunk for res in raw_results for chunk in res]
    ranked = rerank_results(query="đối chiếu bồi thường và chấm dứt hợp đồng", chunks=all_chunks, top_k=4)
    return ranked

results = asyncio.run(run_search())
print(f"Successfully retrieved {len(results)} high-relevance chunks")`,
    },
    {
      id: 'node-3',
      nodeIndex: 3,
      type: 'sandbox_exec',
      title: 'Python Sandbox Execution (gVisor Runtime)',
      subtitle: 'Chạy mã Python trong sandbox bảo mật với cơ chế quản lý bộ nhớ an toàn',
      durationText: `${session.toolTime} · Memory: 42MB`,
      status: 'success',
      stdout: `[gVisor Sandbox: Python 3.12-secure]
> Initializing sandbox environment... [OK]
> Importing sac_sdk primitives... [OK]
> Dispatched 2 parallel async vector queries to Qdrant cluster...
> Received 12 candidate vector chunks in 1.28s.
> Applying Cross-Encoder re-ranker model: bge-reranker-large...
> Retained Top-4 chunks with relevance score >= 0.89.
> Output variables mapped to state filesystem.
> Process completed with Exit Code: 0 (Execution Time: ${session.toolTime})`,
      exitCode: 0,
      memoryMb: 42,
    },
    {
      id: 'node-4',
      nodeIndex: 4,
      type: 'vector_retrieval',
      title: 'Qdrant Vector Retrieval (Top Chunks Matching)',
      subtitle: 'Các phân đoạn tài liệu có độ tương đồng cao nhất được trích xuất từ Qdrant',
      durationText: '1.2s · 4 Chunks',
      status: 'success',
      chunks: [
        {
          document: 'Bao_cao_tai_chinh_nam_2025.pdf',
          page: 14,
          section: 'Mục 8.2: Quy định bồi thường thiệt hại do vi phạm thời hạn',
          score: 0.96,
          textSnippet:
            '...Trong trường hợp Bên B chậm trễ bàn giao quá 15 ngày làm việc, mức phạt vi phạm hợp đồng được ấn định là 0.5% giá trị hợp đồng cho mỗi ngày chậm trễ, nhưng tối đa không quá 8% tổng giá trị hợp đồng...',
        },
        {
          document: 'Kien_truc_he_thong_Search_as_Code.md',
          page: 6,
          section: 'Phần 3.1: Cơ chế xử lý tranh chấp và điều khoản bồi hoàn',
          score: 0.93,
          textSnippet:
            '...Bên vi phạm có nghĩa vụ hoàn trả toàn bộ chi phí thực tế phát sinh và bồi thường thiệt hại trực tiếp được chứng minh bằng hóa đơn chứng từ hợp lệ...',
        },
        {
          document: 'Quy_trinh_bao_mat_du_lieu_2026.docx',
          page: 3,
          section: 'Điều 12: Đơn phương chấm dứt hợp đồng và phạt cọc',
          score: 0.89,
          textSnippet:
            '...Mỗi bên có quyền đơn phương chấm dứt hợp đồng nếu bên kia vi phạm nghiêm trọng nghĩa vụ bảo mật dữ liệu khách hàng theo quy định tại Điều 4...',
        },
      ],
    },
    {
      id: 'node-5',
      nodeIndex: 5,
      type: 'refinement_codegen',
      title: 'Turn 2: Multi-hop Refinement & Kiểm Tra Chéo (Self-Verification)',
      subtitle: 'Agent sinh mã kiểm tra chéo các mốc thời gian và trần phạt tối đa',
      durationText: '24.1s · 680 tokens',
      status: 'success',
      thought:
        'Kiểm toán: Các chunk đã lấy có đầy đủ số liệu phạt vi phạm (0.5%/ngày, tối đa 8%) và quyền đơn phương chấm dứt hợp đồng. Tiến hành tổng hợp và gắn trích dẫn chính xác.',
      code: `# Verify citation alignment and generate grounded claim references
claims = [
    {"claim": "Phạt vi phạm 0.5%/ngày, tối đa 8%", "source": "Bao_cao_tai_chinh_nam_2025.pdf", "page": 14},
    {"claim": "Quyền đơn phương chấm dứt khi vi phạm bảo mật", "source": "Quy_trinh_bao_mat_du_lieu_2026.docx", "page": 3}
]
print("All claims mapped to exact page citations.")`,
    },
    {
      id: 'node-6',
      nodeIndex: 6,
      type: 'grounded_synthesis',
      title: 'Phản Hồi Hoàn Chỉnh & Trích Dẫn Nguồn (Grounded Synthesis)',
      subtitle: 'Tổng hợp câu trả lời cuối cùng với trích dẫn số trang/tệp chuẩn NotebookLM',
      durationText: `${session.llmTime} · Speed: ${session.tokPerSec} tok/s`,
      status: 'success',
      citations: [
        {
          id: 1,
          source: 'Bao_cao_tai_chinh_nam_2025.pdf',
          page: 14,
          quote: 'Mức phạt vi phạm ấn định 0.5% mỗi ngày, trần tối đa 8%',
          verified: true,
        },
        {
          id: 2,
          source: 'Quy_trinh_bao_mat_du_lieu_2026.docx',
          page: 3,
          quote: 'Quyền đơn phương chấm dứt hợp đồng khi vi phạm bảo mật',
          verified: true,
        },
      ],
      answerSnippet: `Dựa trên tài liệu dự án, điều khoản bồi thường và chấm dứt hợp đồng có các điểm mấu chốt sau:
1. **Phạt vi phạm tiến độ [1]**: 0.5% giá trị hợp đồng/ngày chậm trễ, mức phạt tối đa là 8% tổng giá trị.
2. **Quyền đơn phương chấm dứt [2]**: Áp dụng ngay khi phát hiện vi phạm nghĩa vụ bảo mật dữ liệu mà không cần báo trước 30 ngày.`,
    },
  ]

  const toggleNode = (id: string) => {
    setExpandedNodes((prev) => ({ ...prev, [id]: !prev[id] }))
  }

  const toggleAll = (expand: boolean) => {
    const next: Record<string, boolean> = {}
    traceNodes.forEach((n) => {
      next[n.id] = expand
    })
    setExpandedNodes(next)
  }

  const handleCopyCode = (id: string, text: string) => {
    navigator.clipboard.writeText(text)
    setCopiedCodeId(id)
    setTimeout(() => setCopiedCodeId(null), 2000)
  }

  return (
    <Modal
      open={open}
      onClose={onClose}
      title={`Sơ Đồ Cây Thực Thi SaC: ${session.title}`}
      headless
      className={css.modalContainer}
    >
      <div className={css.modalShell}>
        {/* 1. Top Bar */}
        <div className={css.topBar}>
          <div className={css.topBarLeft}>
            <div>
              <div className={css.modalHeaderTitleRow}>
                <h2 id={titleId} className={css.modalTitle}>
                  Sơ Đồ Cây Thực Thi SaC (Execution Trace)
                </h2>
                <span className={css.strategyBadge}>{session.strategy}</span>
              </div>
              <p className={css.modalSubtitle}>
                Phiên: <span className={css.sessionTitleText}>{session.title}</span>
              </p>
            </div>
          </div>

          <div className={css.topBarRight}>
            <div className={css.viewToggle}>
              <button
                type="button"
                className={clsx(css.toggleBtn, activeView === 'tree' && css.toggleBtnActive)}
                onClick={() => setActiveView('tree')}
              >
                Sơ đồ cây
              </button>
              <button
                type="button"
                className={clsx(css.toggleBtn, activeView === 'raw' && css.toggleBtnActive)}
                onClick={() => setActiveView('raw')}
              >
                Raw JSON
              </button>
            </div>
            <button type="button" className={css.closeBtn} onClick={onClose} aria-label="Đóng">
              ✕
            </button>
          </div>
        </div>

        {/* 2. Key Metrics Bar (Wrapped naturally without horizontal scrollbar) */}
        <div className={css.metricsBar}>
          <div className={css.metricPill}>
            <span className={css.pillLabel}>Vòng lặp & Bước:</span>
            <span className={css.pillVal}>{session.turns} turns · {session.steps} steps</span>
          </div>
          <div className={css.metricPill}>
            <span className={css.pillLabel}>Độ trễ:</span>
            <span className={css.pillVal}>LLM {session.llmTime} · Tool {session.toolTime}</span>
          </div>
          <div className={css.metricPill}>
            <span className={css.pillLabel}>Tốc độ sinh:</span>
            <span className={css.pillVal}>{session.ttft} TTFT · {session.tokPerSec} tok/s</span>
          </div>
          <div className={css.metricPill}>
            <span className={css.pillLabel}>Cache Hit:</span>
            <span className={clsx(css.pillVal, css.greenVal)}>{session.cacheHit}%</span>
          </div>
          <div className={css.metricPill}>
            <span className={css.pillLabel}>Trích dẫn:</span>
            <span className={clsx(css.pillVal, css.greenVal)}>{session.citations} ({session.verifiedPct}% Verified)</span>
          </div>
        </div>

        {/* 3. Modal Body */}
        <div className={css.modalBody}>
          {activeView === 'tree' ? (
            <div className={css.treeContainer}>
              <div className={css.treeToolbar}>
                <span className={css.treeStepCount}>Chuỗi 6 bước thực thi Search-as-Code</span>
                <div className={css.treeActions}>
                  <button type="button" className={css.treeTextBtn} onClick={() => toggleAll(true)}>
                    Mở rộng tất cả
                  </button>
                  <span className={css.actionDivider}>·</span>
                  <button type="button" className={css.treeTextBtn} onClick={() => toggleAll(false)}>
                    Thu gọn tất cả
                  </button>
                </div>
              </div>

              {/* Timeline Tree Nodes */}
              <div className={css.timelineList}>
                {traceNodes.map((node, index) => {
                  const isExpanded = !!expandedNodes[node.id]
                  const isLast = index === traceNodes.length - 1

                  return (
                    <div key={node.id} className={clsx(css.timelineItem, isLast && css.timelineItemLast)}>
                      {/* Timeline Connector Line & Dot (Neutral Styling) */}
                      <div className={css.timelineLineCol}>
                        <div className={css.timelineDot}>
                          {node.nodeIndex}
                        </div>
                        {!isLast && <div className={css.timelineLine} />}
                      </div>

                      {/* Node Card */}
                      <div className={css.nodeCard}>
                        {/* Node Card Header (Click to expand/collapse) */}
                        <button
                          type="button"
                          className={css.nodeHeader}
                          onClick={() => toggleNode(node.id)}
                        >
                          <div className={css.nodeHeaderLeft}>
                            <h4 className={css.nodeTitle}>{node.title}</h4>
                            <p className={css.nodeSubtitle}>{node.subtitle}</p>
                          </div>
                          <div className={css.nodeHeaderRight}>
                            <span className={css.nodeDuration}>{node.durationText}</span>
                            <IconChevronDownOutline14
                              size={14}
                              className={clsx(css.chevron, isExpanded && css.chevronOpen)}
                            />
                          </div>
                        </button>

                        {/* Node Collapsible Body */}
                        {isExpanded && (
                          <div className={css.nodeBody}>
                            {/* Thought text */}
                            {node.thought && (
                              <div className={css.thoughtBox}>
                                <span className={css.thoughtLabel}>Tư duy suy luận (CoT Reasoning):</span>
                                <p className={css.thoughtText}>{node.thought}</p>
                              </div>
                            )}

                            {/* Python Code Block */}
                            {node.code && (
                              <div className={css.codeBox}>
                                <div className={css.codeHeader}>
                                  <span className={css.codeLang}>Python (Search-as-Code SDK)</span>
                                  <button
                                    type="button"
                                    className={css.copyCodeBtn}
                                    onClick={() => handleCopyCode(node.id, node.code!)}
                                  >
                                    <IconCopyOutline16 size={13} style={{ marginRight: 4 }} />
                                    <span>{copiedCodeId === node.id ? 'Đã sao chép ✓' : 'Sao chép'}</span>
                                  </button>
                                </div>
                                <pre className={css.codeSnippet}>
                                  <code>{node.code}</code>
                                </pre>
                              </div>
                            )}

                            {/* Sandbox Stdout / Execution Log */}
                            {node.stdout && (
                              <div className={css.stdoutBox}>
                                <div className={css.stdoutHeader}>
                                  <span>Stdout Log (Sandbox Isolated Runtime)</span>
                                  <span className={css.exitCodeBadge}>Exit Code: {node.exitCode ?? 0}</span>
                                </div>
                                <pre className={css.stdoutSnippet}>
                                  <code>{node.stdout}</code>
                                </pre>
                              </div>
                            )}

                            {/* Vector Chunks List */}
                            {node.chunks && node.chunks.length > 0 && (
                              <div className={css.chunksBox}>
                                <span className={css.boxLabel}>Top Chunks Được Trích Xuất (Relevance &ge; 0.89):</span>
                                <div className={css.chunksList}>
                                  {node.chunks.map((c, cIdx) => (
                                    <div key={cIdx} className={css.chunkCard}>
                                      <div className={css.chunkTopRow}>
                                        <span className={css.chunkDocName}>
                                          {c.document} (Trang {c.page})
                                        </span>
                                        <span className={css.chunkScore}>
                                          Score: <strong>{(c.score * 100).toFixed(0)}%</strong>
                                        </span>
                                      </div>
                                      <div className={css.chunkSection}>{c.section}</div>
                                      <p className={css.chunkSnippet}>{c.textSnippet}</p>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            )}

                            {/* Citations and Answer Snippet */}
                            {node.citations && node.citations.length > 0 && (
                              <div className={css.citationsBox}>
                                <span className={css.boxLabel}>Trích Dẫn Kiểm Chứng Nguồn Gốc (NotebookLM Grounding):</span>
                                <div className={css.citationList}>
                                  {node.citations.map((cite) => (
                                    <div key={cite.id} className={css.citationPill}>
                                      <span className={css.citeId}>[{cite.id}]</span>
                                      <span className={css.citeSource}>{cite.source} : Trang {cite.page}</span>
                                      <span className={css.verifiedBadge}>✓ 100% Verified</span>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            )}

                            {node.answerSnippet && (
                              <div className={css.answerBox}>
                                <span className={css.boxLabel}>Bản Trích Câu Trả Lời:</span>
                                <p className={css.answerText}>{node.answerSnippet}</p>
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          ) : (
            /* RAW JSON VIEW */
            <div className={css.rawJsonContainer}>
              <div className={css.rawJsonToolbar}>
                <span className={css.rawJsonLabel}>Telemetry Trace Payload (Langfuse / OpenInference format)</span>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handleCopyCode('raw-json', JSON.stringify(traceNodes, null, 2))}
                >
                  <IconCopyOutline16 size={13} style={{ marginRight: 6 }} />
                  <span>{copiedCodeId === 'raw-json' ? 'Đã sao chép ✓' : 'Sao chép JSON'}</span>
                </Button>
              </div>
              <pre className={css.rawJsonSnippet}>
                <code>{JSON.stringify(traceNodes, null, 2)}</code>
              </pre>
            </div>
          )}
        </div>

        {/* 4. Modal Footer */}
        <div className={css.modalFooter}>
          <div className={css.footerLeft}>
            <span className={css.footerSessionInfo}>
              ID: <code className={css.codeId}>{session.id}</code> · {session.date}
            </span>
          </div>
          <div className={css.footerActions}>
            <Button
              variant="primary"
              size="sm"
              onClick={() => {
                onClose()
                navigateToChat(session.id, project.id)
              }}
            >
              <IconSparkle16 size={14} style={{ marginRight: 6 }} />
              <span>Mở phiên chat này</span>
            </Button>
            <Button variant="outline" size="sm" onClick={onClose}>
              Đóng
            </Button>
          </div>
        </div>
      </div>
    </Modal>
  )
}
